apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: ericsakamoto/app-a:latest
        env:
        - name: APP_B_URL
          value: http://app-b:5000/process
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://127.0.0.1:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_SERVICE_NAME
          value: "my-python-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=prod,service.version=1.0.0"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "otlp"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        ports:
        - containerPort: 5000
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.107.0
        args: ["--config=/etc/otelcol/config.yaml"]
        ports:
          - name: otlp-http
            containerPort: 4318
        envFrom:
          - secretRef:
              name: grafana-cloud-credentials
        volumeMounts:
          - name: otel-config
            mountPath: /etc/otelcol
      volumes:
        - name: otel-config
          configMap:
            name: otelcol-config
            items:
              - key: config.yaml
                path: config.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  type: LoadBalancer
  selector:
    app: app-a
  ports:
  - protocol: TCP
    port: 443
    targetPort: 5000
